### ISSUE TITLE
Do do list

### ISSUE THREAD

**Issue by melanybelzile** [DFOglider/pilotingApp#1]
* [x] Adding the navigation plots of glider speed and travelled distance
* [x] Plotting all the science data (including a dynamic map of the glider path with bathy data)

**Comment by richardsc** [comment]
Awesome. FYI I updated your comment using some "Markdown" formatting to make little checkboxes. If you click on the "pencil" icon you can see what I did. If you want to add your own formatting (bullets, numbered lists, code chunks, etc), click on the little "Styling with Markdown is supported" link under the editing window to get some hints.

:smile:
