### ISSUE TITLE
Need a "Downloading" data dialog when the data are being downloaded

### ISSUE THREAD

**Issue by richardsc** [DFOglider/pilotingApp#10]
Especially when the app is run on a server, there is no indication that it has gone and is downloading files.

**Comment by clayton33** [comment]
came across this package a few weeks ago, https://github.com/dreamRs/shinyWidgets , check out sendSweetAlert, could be an option if this feature is still desired.

**Comment by richardsc** [comment]
I saw this on Rbloggers the other day, looks like some useful ideas here:
http://blog.fellstat.com/?p=407
