### ISSUE TITLE
Add another tab for a TS plot

### ISSUE THREAD

**Issue by richardsc** [DFOglider/pilotingApp#13]
Same functionality as the profiles tab, but just a single TS plot. Profile numbers could be used to colour the lines by time.

**Comment by richardsc** [comment]
Or, there could be a sub-menu that allows for coloring of the points based on any number of the other nav/science fields, e.g.:
* profile number
* lat/lon
* distance
* time
* pressure
* up/down
* any science field

One issue I foresee with coloring based on either nav or sci fields is that they are on different time bases. So there might have to be some interpolation to get things to match up.

**Comment by clayton33** [comment]
I'm closing this cuz you've done it, minus the colour coding, so you can re-open if it you want.
