### ISSUE TITLE
Reloading after ~200 profiles becomes quite slow

### ISSUE THREAD

**Issue by richardsc** [DFOglider/pilotingApp#18]
I'm sure this is because each time it reloads it re-processes the entire data set. Would make sense to just look for new files and append them to an already processed (and saved) `.rda` file.

**Comment by clayton33** [comment]
I believe I have addressed this issue, going to test it for a day or two before pushing.

**Comment by richardsc** [comment]
Can you push on a separate branch? That way I can test too.

**Comment by clayton33** [comment]
created branch `cl-issue18` so you can test it.

**Comment by clayton33** [comment]
Closing this, if there's something that needs to be fixed we can re-open. I'll do a pull request later today.

**Comment by richardsc** [comment]
This looks like it works well, but there are merge conflicts with `master`, so let's keep this open until you've merged (either directly or with a PR) and we have tested `master` after the merge.

**Comment by clayton33** [comment]
Ok. I'll take a look at the conflicts, fix them and then do a PR.
