### ISSUE TITLE
Experiment with text box input vs pull down for profile tab

### ISSUE THREAD

**Issue by richardsc** [DFOglider/pilotingApp#19]
From Dave:

> On the profile tab, i prefer a box to enter the values rather that a pull down when you have 600+ profiles.

**Comment by clayton33** [comment]
Branch `cl-issue19` addresses this issue, others can play with it to see if they like it before I make a pull request.

**Comment by clayton33** [comment]
Closing this, if there's something that needs to be fixed we can re-open. I'll do a pull request later today.

**Comment by richardsc** [comment]
I've merged
