### ISSUE TITLE
firmware update fixes : 0,0 position for map and date in first dive

### ISSUE THREAD

**Issue by clayton33** [DFOglider/pilotingApp#30]
Not sure how the 0,0 position is an issue again, looking at the code in ``app.R``, lines 735 - 736 are commented out, there might be a reason, but right now I don't remember.

Prior to the firmware update, there were always some data points which had a 2009 timestamp. With the new updates, the new timestamp issue is 2018-07-12. Based on the basin tests for SEA024 and SEA032, both do not have the same hh:mm:ss or same number of data points. Right now, we replace the 2009 timestamps with NA's in ``readSeaExplorerRealTime.R`` on line 92 and 242 for the navigation and payload files respectively.  I think the easiest way of dealing with this is to note the missions for each glider prior to the firmware updates and check if the mission is before or after. This might be an issue down the road if we plan on recycling mission names when we hit M99 for each glider.

These fixes are not critical right now. As requested by @melanybelzile, they will not be pushed to the server until after the Bonavista mission.

**Comment by clayton33** [comment]
Both issues have been fixed. Lines 95-96 in ``readSeaExplorerRealTime.R`` will need to be updated as we update the firmware on the gliders. I tested it with a few of our previous missions and it seems to be working a-ok.

I've pushed these changes to the ``firmwareFixes`` branch, and merged it with the ``mapUpdates`` branch as I think this is the current version on the web.

**Comment by richardsc** [comment]
Cool. I pulled on the server but it looks like `mapUpdates` doesn't have any of the new changes. Is that what you intended?

**Comment by clayton33** [comment]
What I meant was that i merged mapUpdates into firmwareFixes.

**Comment by richardsc** [comment]
Ah, that explains it. When you've finished testing and merge `firmwareFixes` back into `mapUpdates`, let me know and I'll update on the server.

**Comment by richardsc** [comment]
Is this good to merge? It's driving me nuts every time I look at LaHave on mission 26 and have to zoom in ... :stuck_out_tongue:

**Comment by clayton33** [comment]
Yes, I'm confident that its good to go. I'm fairly certain that all of my changes have been pushed. Windows is claiming that it can't find the ``git`` command this morning, ugh.

**Comment by clayton33** [comment]
Got ``git`` working, ``firmwareFixes`` is up to date and can be merged.

**Comment by clayton33** [comment]
All of the gliders have been upgraded to the new firmware, but the app is behind.

- SEA019, M54
- SEA021, M39
- SEA022, M34
