### ISSUE TITLE
add slider bar to control ylim of navigation plots

### ISSUE THREAD

**Issue by clayton33** [DFOglider/pilotingApp#46]
Requested by DH to add slider bar (similar to that for the science plots) to control the ylim for the plots. Below is a summary of the ranges for each variable that I'll use and the step.

- Altimeter, min = 0, max = 100, step = 1
- Alarm, min = 0, max = 1e6, step = 1e3
- Pitch, min = -80, max = 50, step = 5
- Vertical Speed, min = -50, max = 50, step = 5
- Battery Voltage, min = 24, max = 30, step = 0.05
- Battery Percentage, min = 0, max = 100, step = 1
- Internal Temperature, min = 0, max = 26, step = 1
- Internal Pressure, min = 7.1e4, max = 7.7e4, step = 50
- Distance, min = 0, max = 1000, step = 50
- Speed, min = 0, max = 2, step = 0.1
- Heading, min = 0, max = 350, step = 10
- Ballast, min = -500, max = 500, step = 25
- Angular, min = -70, max = 70, step = 5
- Linear, min = 20, max = 100, step = 5
- Roll, min = -20, max = 30, step = 5
- Yo Numbers, min = 0, max = 1200, step = 20

Note that I might see if I can make the slider be reactive for Alarm, Distance, and Yo Numbers. After writing all this down, it might be better to add a brush on the bottom plot if the y-direction only just so we don't have to fuss with the slider throwing an error if values are outside the expected range or there isn't enough variation in the data, like we sometimes do with the slider for the science plots.

**Comment by melanybelzile** [comment]
Altimeter, min = 0, max = 60, step = 1
Alarm, min = 0, max = 5.5e5, step = 1e3, defalt 0, 5000. but would be even better with a log scale
Internal Temperature, min = 0, max = 30, step = 1
Internal Pressure, min = 7.1e4, max = 8.1e4, step = 50
Distance, min = 0, max = 700, step = 50
Speed, min = 0, max = 2, step = 0.1, default 0, 1.
Ballast, I dont see the bleue line anymore
Yo Numbers, min = 0, max = 1500, step = 50
