### ISSUE TITLE
Making the app work without all kind of files

### ISSUE THREAD

**Issue by melanybelzile** [DFOglider/pilotingApp#5]
It would be nice to be able to run the app when there is only 1 or 2 data file type out of 3 (Science, Nav, KML). Right now, the app need at least one of each to be able to work but let say the communication is bad while deploying and we were able to retrieve the first 2 nav files. It would be nice to be able to adjust the pitch and speed while we are waiting for better satellite coverage to get a science file.

**Comment by richardsc** [comment]
Just to keep track of things, I may have made this worse with the changes in the `profilePlots` branch to fix issue #6 ... the fix there was to just skip the first profile, but in the case where this is only 1 dive that will cause problems ...

**Comment by melanybelzile** [comment]
hmm yeah, the 2 issues are confrontational* We can talk about it tomorrow, I'll be in the lab part of the afternoon.

* I looked for 'conflictuel' translation

**Comment by richardsc** [comment]
"conflicting" 😄
